// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';


var height = 320;

var width = 568;

var minOffset = -600;

var maxOffset = 600;

var roadWidth = 680;

var frameRate = 60;

exports.height = height;
exports.width = width;
exports.minOffset = minOffset;
exports.maxOffset = maxOffset;
exports.roadWidth = roadWidth;
exports.frameRate = frameRate;
/* No side effect */
