// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';


function isLeft(state) {
  if (state[/* left */1]) {
    return !state[/* right */0];
  } else {
    return false;
  }
}

function isRight(state) {
  if (state[/* right */0]) {
    return !state[/* left */1];
  } else {
    return false;
  }
}

function isBrake(state) {
  return state[/* brake */2];
}

function isReset(state) {
  return state[/* reset */3];
}

function getTurn(state) {
  var match = isRight(state);
  var match$1 = isLeft(state);
  var match$2 = state[/* brake */2];
  if (match) {
    if (match$1) {
      return /* NONE */4;
    } else if (match$2) {
      return /* P_RIGHT */3;
    } else {
      return /* RIGHT */2;
    }
  } else if (match$1) {
    if (match$2) {
      return /* P_LEFT */1;
    } else {
      return /* LEFT */0;
    }
  } else {
    return /* NONE */4;
  }
}

function keyDown(code, state) {
  if (code >= 51) {
    switch (code - 51 | 0) {
      case 0 : 
          return /* record */[
                  /* right */true,
                  /* left */state[/* left */1],
                  /* brake */state[/* brake */2],
                  /* reset */state[/* reset */3]
                ];
      case 1 : 
          return /* record */[
                  /* right */state[/* right */0],
                  /* left */true,
                  /* brake */state[/* brake */2],
                  /* reset */state[/* reset */3]
                ];
      case 2 : 
          return /* record */[
                  /* right */state[/* right */0],
                  /* left */state[/* left */1],
                  /* brake */true,
                  /* reset */state[/* reset */3]
                ];
      case 3 : 
          return /* record */[
                  /* right */state[/* right */0],
                  /* left */state[/* left */1],
                  /* brake */state[/* brake */2],
                  /* reset */true
                ];
      case 4 : 
      case 5 : 
      case 6 : 
      case 7 : 
      case 8 : 
      case 9 : 
      case 10 : 
      case 11 : 
      case 12 : 
      case 13 : 
      case 14 : 
          return state;
      
    }
  } else {
    return state;
  }
}

function keyUp(code, state) {
  if (code >= 51) {
    switch (code - 51 | 0) {
      case 0 : 
          return /* record */[
                  /* right */false,
                  /* left */state[/* left */1],
                  /* brake */state[/* brake */2],
                  /* reset */state[/* reset */3]
                ];
      case 1 : 
          return /* record */[
                  /* right */state[/* right */0],
                  /* left */false,
                  /* brake */state[/* brake */2],
                  /* reset */state[/* reset */3]
                ];
      case 2 : 
          return /* record */[
                  /* right */state[/* right */0],
                  /* left */state[/* left */1],
                  /* brake */false,
                  /* reset */state[/* reset */3]
                ];
      case 3 : 
          return /* record */[
                  /* right */state[/* right */0],
                  /* left */state[/* left */1],
                  /* brake */state[/* brake */2],
                  /* reset */false
                ];
      case 4 : 
      case 5 : 
      case 6 : 
      case 7 : 
      case 8 : 
      case 9 : 
      case 10 : 
      case 11 : 
      case 12 : 
      case 13 : 
      case 14 : 
          return state;
      
    }
  } else {
    return state;
  }
}

var init = /* record */[
  /* right */false,
  /* left */false,
  /* brake */false,
  /* reset */false
];

exports.init = init;
exports.isLeft = isLeft;
exports.isRight = isRight;
exports.isBrake = isBrake;
exports.isReset = isReset;
exports.getTurn = getTurn;
exports.keyDown = keyDown;
exports.keyUp = keyUp;
/* No side effect */
