// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Reprocessing = require("/Users/jim/Github/returbo/node_modules/reprocessing/src/Reprocessing.js");

Reprocessing.hotreload(undefined, "src/index.re");

/*  Not a pure module */
