// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Reprocessing_Draw = require("/Users/jim/Github/returbo/node_modules/reprocessing/src/Reprocessing_Draw.js");

function scoreString(state) {
  return String(state[/* score */0] / 10 | 0);
}

function increment(x, state) {
  return /* record */[/* score */state[/* score */0] + x];
}

function draw(state, env) {
  var score = scoreString(state);
  return Reprocessing_Draw.text(undefined, score, /* tuple */[
              60,
              20
            ], env);
}

var init = /* record */[/* score */0];

exports.scoreString = scoreString;
exports.increment = increment;
exports.init = init;
exports.draw = draw;
/* Reprocessing_Draw Not a pure module */
